version: '3'

services:

  node:
    image: node-app:v1
    build: 
        context: ./dockerfiles
        dockerfile: Dockerfile.node
    network_mode: bridge
    restart: always
    ports:
            - 8081:8081
  db:
    image: postgres:10
    network_mode: bridge
    restart: always
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
  spring-boot:
    image: spring-boot-app:v1
    build: 
        context: ./dockerfiles
        dockerfile: Dockerfile.spring
    network_mode: bridge
    restart: always
    ports:
            - 8080:8080
    links:
            - db
            - node
